version: "3"
services:
  namenode:
    image: dhimasarbi/hadoop:3.3.4
    command: bash -c "/home/hadoop/hadoop-cmd.sh start namenode"
    hostname: namenode
    environment:
      - HADOOP_HOSTNAME=namenode
    ports:
      - target: 9870
        published: 9870
        protocol: tcp
        mode: host
      - "9000:9000"
      - "9868:9868"
      - "50070:50070"
      - "8088:8080"
    volumes:
      - hdfs-master-data:/home/hadoop/data/nameNode
      - /hadoop-conf:/usr/local/hadoop/etc/hadoop
      - /hadoop/namenode_data:/data
      - /hadoop/user_data:/user_data
    networks:
      - cluster-net
    deploy:
      mode: global
      endpoint_mode: dnsrr
      replicas: 1
      placement:
        constraints: [node.hostname == namenode]

  datanode:
    image: dhimasarbi/hadoop:3.3.4
    command: bash -c "/home/hadoop/hadoop-cmd.sh start"
    depends_on:
      - "namenode"
    ports:
      - "9867:9867"
      - "9866:9866"
      - "9865:9865"
      - "9864:9864"
      - "50075:50075"
    volumes:
      - hdfs-worker-data:/home/hadoop/data/dataNode
      - /hadoop-conf:/usr/local/hadoop/etc/hadoop
      - /hadoop/datanode_data:/data
    networks:
      - cluster-net
    deploy:
      replicas: 2
      placement:
        constraints: [node.hostname != namenode]

volumes:
  hdfs-master-data:
    external: true
    name: "hdsf_master_data_swarm"
  hdfs-master-checkpoint-data:
    external: true
    name: "hdsf_master_checkpoint_data_swarm"
  hdfs-worker-data:
    external: true
    name: "hdsf_worker_data_swarm"

networks:
  cluster-net:
    driver: overlay
    attachable: true
    external: true
    name: cluster_net_swarm
